### PR TITLE
Replaced occurences of gets(), Removed dead links, Cleanse README

### PR DESCRIPTION
**Pull request by adi-g15**
**1. Replaced occurences of gets() with fgets() from code ->** _gets() was deprecated in C++11, and removed in C++14, due to its flaws. And some C implementations have it, but most will give warning_

[Why gets() shouldn't be used, and was removed](https://stackoverflow.com/questions/1694036/why-is-the-gets-function-so-dangerous-that-it-should-not-be-used#1694042)

**2. Removed dead links ->** There were many links to dead links from 2012 or so, only working links are now present

**3. Removed a string.in and an old readme file which was simply a text file, providing sample input ->**  It has been used nowhere. And the older readme had the _same but lesser_ content

**4. Cleanse the README ->** Fixed some markdownlint errors, that make the readme look better now. The balloon links in starting were dead too, have been replaced with emojis with same UTF number.
Mostly, chinese translations have been converted to english, to support easier searching for a particular topic, the original repo will continue to have chinese if needed

### CODE REVIEW

**Comment by adi-g15** [comment]
Though the readme.md in files changes section shows 'Large diffs are not rendered by default', it can be easily rendered and should be seen upon :D

And, the codes in the README are working, their has been tampering only with the gets() parts.

**Comment by adi-g15** [comment]
@tinfoil-knight @garimasingh128 Take a look at this PR, it makes it easier to go through the content in Readme in English (since part of it is chinese, though that would have been a personal preference), removing dead links to resources. Or maybe if it alters the idea, the PR maybe closed too :)

**Comment by tinfoil-knight** [comment]
@adi-g15 Since there's no activity, could you just close the issue. I don't have write access to merge the PR.

**Comment by adi-g15** [comment]
Okay, there was no activity for a very long time now

**Pull request merged**
